"""add_example_model.

Revision details for database migration.

Revision ID: bfc352b2be97
Revises: 
Create Date: 2026-10-01 16:56:41.518848
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc352b2be97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_created_at'), 'example', ['created_at'], unique=False)
    op.create_index(op.f('ix_example_id'), 'example', ['id'], unique=True)
    op.create_index(op.f('ix_example_updated_at'), 'example', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_updated_at'), table_name='example')
    op.drop_index(op.f('ix_example_id'), table_name='example')
    op.drop_index(op.f('ix_example_created_at'), table_name='example')
    op.drop_table('example')
    # ### end Alembic commands ###
